---
- name: Configure zabbix agent for veeam agent
  hosts: linux
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure required directories exists
      file:
        path: /var/lib/zabbix/veeam
        state: directory

    - name: Add zabbix to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'zabbix  ALL=(ALL)     NOPASSWD: ALL'

    - name: Copy veeamlog.sh
      copy:
        src: ./config/veeamlog.sh
        dest: /var/lib/zabbix/veeam/veeamlog.sh
        owner: zabbix
        group: zabbix
        mode: 0755
      register: veeamlog_sh
    
    - name: Copy veeamlog.conf
      copy:
        src: ./config/veeamlog-linux.conf
        dest: /etc/zabbix/zabbix_agentd.d/template_veeamlog.conf
      register: veeamlog_conf

    - name: Restart zabbix-agent service
      service:
        name: zabbix-agent
        state: restarted